name: Build and Push Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build Linux executable
        run: |
          pyinstaller --onefile sman.py
          mkdir -p dist/linux
          mv dist/sman dist/linux/sman

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and Push Changes
        run: |
          git add dist/linux/sman
          git commit -m "Add Linux executable"
          git remote add "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" https://github.com/sabbir28/S_man.git
          git push --quiet --set-upstream "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" main

