name: Build Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Install Wine for Windows build
      run: |
        sudo apt-get update
        sudo apt-get install -y wine

    - name: Build Linux executable
      run: |
        pyinstaller --onefile sman.py
        mkdir -p dist/linux
        mv dist/sman dist/linux/sman

    - name: Build Windows executable using Wine
      run: |
        wine pyinstaller --onefile sman.py
        mkdir -p dist/windows
        mv dist/sman.exe dist/windows/sman.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executables
        path: dist/
